export const TITLE_CHANGE = 'TITLE_CHANGE';
export const YEAR_CHANGE = 'YEAR_CHANGE';

export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILED = 'SEARCH_MOVIES_FAILED';

export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED';

export const PAGE_NUMBER_CHANGE = 'PAGE_NUMBER_CHANGE';

export const TYPE_CHANGED = 'TYPE_CHANGED';

export const SORT_RESULTS = 'SORT_RESULTS';